[
  {
    "id": "seed-001",
    "title": "Bathroom & Kitchen Tiling Specialist",
    "category": "Home & Garden",
    "location": "Polokwane CBD",
    "description": "10 years experience in ceramic, porcelain, and mosaic tiling. Floors, walls, custom patterns. Free quote within 24 hours. – R1 200 per job",
    "sellerName": "Thabo's Tiling",
    "sellerPhone": "082 123 4501",
    "image": "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400",
    "status": "approved",
    "submittedAt": "2026-06-01",
    "plan": "4months",
    "planPrice": 480,
    "paid": true,
    "expiresAt": null
  },
  {
    "id": "seed-002",
    "title": "Full Garden Makeover & Landscaping",
    "category": "Home & Garden",
    "location": "Bendor, Polokwane",
    "description": "From overgrown to outstanding. Planting, lawn, irrigation, garden lighting. Weekly maintenance available. – From R850",
    "sellerName": "GreenThumb Landscapes",
    "sellerPhone": "082 123 4502",
    "image": "https://images.unsplash.com/photo-1558904541-ef8433a34f6b?w=400",
    "status": "approved",
    "submittedAt": "2026-06-02",
    "plan": "4months",
    "planPrice": 480,
    "paid": true,
    "expiresAt": null
  },
  {
    "id": "seed-003",
    "title": "Ladies' Hair Styling & Braiding Salon",
    "category": "Beauty",
    "location": "Seshego, Polokwane",
    "description": "Knotless braids, twists, weaves, colour treatments. Premium products. Walk‑ins welcome. – R450 per style",
    "sellerName": "Glow Hair Studio",
    "sellerPhone": "082 123 4503",
    "image": "https://images.unsplash.com/photo-1562322140-8baeececf3df?w=400",
    "status": "approved",
    "submittedAt": "2026-06-03",
    "plan": "4months",
    "planPrice": 480,
    "paid": true,
    "expiresAt": null
  },
  {
    "id": "seed-004",
    "title": "Same‑Day Parcel Delivery Service",
    "category": "Logistics",
    "location": "Polokwane to Pretoria/JHB",
    "description": "Reliable door‑to‑door delivery for packages up to 30kg. Real‑time tracking. Same‑day collection. – From R150",
    "sellerName": "SwiftCourier SA",
    "sellerPhone": "082 123 4504",
    "image": "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400",
    "status": "approved",
    "submittedAt": "2026-06-04",
    "plan": "4months",
    "planPrice": 480,
    "paid": true,
    "expiresAt": null
  },
  {
    "id": "seed-005",
    "title": "Precision Haircuts for Men & Boys",
    "category": "Beauty",
    "location": "Polokwane CBD",
    "description": "Classic cuts, fades, beard trims, hot towel shaves. Walk‑in only. Student discounts. – R200",
    "sellerName": "The Barber's Chair",
    "sellerPhone": "082 123 4505",
    "image": "https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=400",
    "status": "approved",
    "submittedAt": "2026-06-05",
    "plan": "4months",
    "planPrice": 480,
    "paid": true,
    "expiresAt": null
  },
  {
    "id": "seed-006",
    "title": "Laundry & Ironing – Pickup & Deliver",
    "category": "Cleaning",
    "location": "Bendor",
    "description": "Wash, dry, fold, iron. Same‑day return available. Eco‑friendly detergents. First wash free. – R300 per load",
    "sellerName": "FreshLinens Laundry",
    "sellerPhone": "082 123 4506",
    "image": "https://images.unsplash.com/photo-1545173168-9f1947eebb7f?w=400",
    "status": "approved",
    "submittedAt": "2026-06-06",
    "plan": "4months",
    "planPrice": 480,
    "paid": true,
    "expiresAt": null
  },
  {
    "id": "seed-007",
    "title": "Indoor Maintenance – Plumbing & Electrical",
    "category": "Home & Garden",
    "location": "Polokwane – All areas",
    "description": "Fixing leaks, geysers, rewiring, fault finding. Licensed and insured. 24/7 emergency. – R950",
    "sellerName": "FixIt All Services",
    "sellerPhone": "082 123 4507",
    "image": "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400",
    "status": "approved",
    "submittedAt": "2026-06-07",
    "plan": "4months",
    "planPrice": 480,
    "paid": true,
    "expiresAt": null
  },
  {
    "id": "seed-008",
    "title": "Certified Electrician – Residential & Commercial",
    "category": "Home & Garden",
    "location": "Seshego",
    "description": "DB board upgrades, lighting, solar prep, general electrical work. COC issued. 5‑year guarantee. – R1 100",
    "sellerName": "VoltSafe Electrical",
    "sellerPhone": "082 123 4508",
    "image": "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=400",
    "status": "approved",
    "submittedAt": "2026-06-08",
    "plan": "4months",
    "planPrice": 480,
    "paid": true,
    "expiresAt": null
  },
  {
    "id": "seed-009",
    "title": "Garden Pruning & Tree Felling",
    "category": "Home & Garden",
    "location": "Bendor, Polokwane",
    "description": "Safe tree removal, stump grinding, hedge trimming, palm maintenance. Fully insured arborists. – From R600",
    "sellerName": "TreeCare Pros",
    "sellerPhone": "082 123 4509",
    "image": "https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?w=400",
    "status": "approved",
    "submittedAt": "2026-06-09",
    "plan": "4months",
    "planPrice": 480,
    "paid": true,
    "expiresAt": null
  }
]
